services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server:/app

  client:
    build: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app
